[auth]
users = ["Nigel"]            # gebruikersnaam
passwords = ["Fcutreg50"]  # wachtwoord (simpel, 1-op-1 match per index)

# (optioneel) je kunt meerdere gebruikers toevoegen:
# users = ["admin","collega"]
# passwords = ["wachtwoord1","wachtwoord2"]
